/*
 * CarvingCategory.java
 *
 * Generated with Matisse Schema Definition Language 9.1.8
 * Generation date: Thu Apr 07 21:16:53 2016
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

import com.matisse.reflect.*;

/**
 * <code>CarvingCategory</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class CarvingCategory extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.8
     * Generation Date: Thu Apr 07 21:16:53 2016
     */

    /*
     * Class variables and methods
     */

    /** Class <code>CarvingCategory</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("CarvingCategory"));

    /**
     * Gets the <code>CarvingCategory</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public CarvingCategory(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected CarvingCategory(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(CarvingCategory.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, CarvingCategory.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(CarvingCategory.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, CarvingCategory.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'CarvingMaterial' */

    /** Attribute <code>CarvingMaterial</code> cache ID */
    private static int carvingMaterialCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("CarvingMaterial",CID));

    /**
     * Gets the <code>CarvingMaterial</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getCarvingMaterialAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(carvingMaterialCID);
    }


    /**
     * Gets the <code>CarvingMaterial</code> attribute value.
     * @return the value
     *
     * @see #setCarvingMaterial
     * @see #removeCarvingMaterial
     */
    public final String getCarvingMaterial() {
        return getString(getCarvingMaterialAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>CarvingMaterial</code> attribute value.
     * @param val the new value
     *
     * @see #getCarvingMaterial
     * @see #removeCarvingMaterial
     */
    public final void setCarvingMaterial(String val) {
        setString(getCarvingMaterialAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>CarvingMaterial</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getCarvingMaterial
     * @see #setCarvingMaterial
     */
    public final void removeCarvingMaterial() {
        removeValue(getCarvingMaterialAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getCarvingMaterial
     * @see #setCarvingMaterial
     */
    public final boolean isCarvingMaterialDefaultValue() {
        return isDefaultValue(getCarvingMaterialAttribute(getMtDatabase()));
    }

    /* EntryPoint 'findCarvingCategory' of attribute 'CarvingMaterial' */

    /** EntryPointDictionary <code>findCarvingCategory</code> cache ID */
    private static int findCarvingCategoryDictionaryCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtEntryPointDictionary.Loader("findCarvingCategory"));

    /**
     * Gets the <code>findCarvingCategory</code> entry point dictionary descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the dictionary
     * @return the entry point dictionary descriptor object
     */
    public static com.matisse.reflect.MtEntryPointDictionary getFindCarvingCategoryDictionary(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtEntryPointDictionary)db.getCachedObject(findCarvingCategoryDictionaryCID);
    }

    /**
     * Finds the <code>CarvingCategory</code> object where <code>CarvingMaterial</code> matches this value.
     * @param db a database
     * @param value the search string
     * @return the matching <code>CarvingCategory</code> or <code>null</code> if none was found
     * @throws MtException if more than one match found
     */
    public static CarvingCategory lookupFindCarvingCategory(com.matisse.MtDatabase db, String value) {
        return (CarvingCategory)getFindCarvingCategoryDictionary(db).lookup(value, getClass(db));
    }

    /**
     * Creates an iterator on all <code>CarvingCategory</code> objects where <code>CarvingMaterial</code> matches this value.
     * @param <E> a MtObject class     * @param db a database
     * @param value the search string
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> findCarvingCategoryIterator(com.matisse.MtDatabase db, String value) {
        return getFindCarvingCategoryDictionary(db).<E>iterator(value, getClass(db), CarvingCategory.class);
    }

    /**
     * Creates an iterator on all <code>CarvingCategory</code> objects where <code>CarvingMaterial</code> matches this value.
     * Use this method to restrict the iterator to members of a subclass of this class,
     * or to set a maximum number of objects.
     * @param <E> a MtObject class     * @param db a database
     * @param value the search string
     * @param filterClass a subclass; use <code>null</code> not to restrict iterator to a subclass
     * @param numObjPerBuffer maximum number of objects to include in the iterator
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> findCarvingCategoryIterator(com.matisse.MtDatabase db, String value, com.matisse.reflect.MtClass filterClass, int numObjPerBuffer) {
        return getFindCarvingCategoryDictionary(db).<E>iterator(value, filterClass, numObjPerBuffer, CarvingCategory.class);
    }


    /* Attribute 'CarvingDimension' */

    /** Attribute <code>CarvingDimension</code> cache ID */
    private static int carvingDimensionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("CarvingDimension",CID));

    /**
     * Gets the <code>CarvingDimension</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getCarvingDimensionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(carvingDimensionCID);
    }


    /**
     * Gets the <code>CarvingDimension</code> attribute value.
     * @return the value
     *
     * @see #setCarvingDimension
     * @see #removeCarvingDimension
     */
    public final String getCarvingDimension() {
        return getString(getCarvingDimensionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>CarvingDimension</code> attribute value.
     * @param val the new value
     *
     * @see #getCarvingDimension
     * @see #removeCarvingDimension
     */
    public final void setCarvingDimension(String val) {
        setString(getCarvingDimensionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>CarvingDimension</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getCarvingDimension
     * @see #setCarvingDimension
     */
    public final void removeCarvingDimension() {
        removeValue(getCarvingDimensionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getCarvingDimension
     * @see #setCarvingDimension
     */
    public final boolean isCarvingDimensionDefaultValue() {
        return isDefaultValue(getCarvingDimensionAttribute(getMtDatabase()));
    }


    /* Attribute 'CarvingWeight' */

    /** Attribute <code>CarvingWeight</code> cache ID */
    private static int carvingWeightCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("CarvingWeight",CID));

    /**
     * Gets the <code>CarvingWeight</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getCarvingWeightAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(carvingWeightCID);
    }


    /**
     * Gets the <code>CarvingWeight</code> attribute value.
     * @return the value
     *
     * @see #setCarvingWeight
     * @see #removeCarvingWeight
     */
    public final int getCarvingWeight() {
        return getInteger(getCarvingWeightAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>CarvingWeight</code> attribute value.
     * @param val the new value
     *
     * @see #getCarvingWeight
     * @see #removeCarvingWeight
     */
    public final void setCarvingWeight(int val) {
        setInteger(getCarvingWeightAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>CarvingWeight</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getCarvingWeight
     * @see #setCarvingWeight
     */
    public final void removeCarvingWeight() {
        removeValue(getCarvingWeightAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getCarvingWeight
     * @see #setCarvingWeight
     */
    public final boolean isCarvingWeightDefaultValue() {
        return isDefaultValue(getCarvingWeightAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'from_carving' */

    /** Relationship <code>from_carving</code> cache ID */
    private static int from_carvingCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("from_carving",CID));

    /**
     * Gets the <code>from_carving</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getFrom_carvingRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(from_carvingCID);
    }

    /**
     * Gets the <code>from_carving</code> sucessor object.
     * @return an object 
     */
    public final ArtItem getFrom_carving() {
        return (ArtItem)getSuccessor(getFrom_carvingRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public CarvingCategory(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[CarvingCategory]";
    }
}
