/*
 * PaintingCategory.java
 *
 * Generated with Matisse Schema Definition Language 9.1.8
 * Generation date: Thu Apr 07 21:16:53 2016
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

import com.matisse.reflect.*;

/**
 * <code>PaintingCategory</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class PaintingCategory extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.8
     * Generation Date: Thu Apr 07 21:16:53 2016
     */

    /*
     * Class variables and methods
     */

    /** Class <code>PaintingCategory</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("PaintingCategory"));

    /**
     * Gets the <code>PaintingCategory</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public PaintingCategory(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected PaintingCategory(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(PaintingCategory.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, PaintingCategory.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(PaintingCategory.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, PaintingCategory.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'PaintingMedium' */

    /** Attribute <code>PaintingMedium</code> cache ID */
    private static int paintingMediumCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("PaintingMedium",CID));

    /**
     * Gets the <code>PaintingMedium</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getPaintingMediumAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(paintingMediumCID);
    }


    /**
     * Gets the <code>PaintingMedium</code> attribute value.
     * @return the value
     *
     * @see #setPaintingMedium
     * @see #removePaintingMedium
     */
    public final String getPaintingMedium() {
        return getString(getPaintingMediumAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>PaintingMedium</code> attribute value.
     * @param val the new value
     *
     * @see #getPaintingMedium
     * @see #removePaintingMedium
     */
    public final void setPaintingMedium(String val) {
        setString(getPaintingMediumAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>PaintingMedium</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getPaintingMedium
     * @see #setPaintingMedium
     */
    public final void removePaintingMedium() {
        removeValue(getPaintingMediumAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getPaintingMedium
     * @see #setPaintingMedium
     */
    public final boolean isPaintingMediumDefaultValue() {
        return isDefaultValue(getPaintingMediumAttribute(getMtDatabase()));
    }

    /* EntryPoint 'findPaintingCategory' of attribute 'PaintingMedium' */

    /** EntryPointDictionary <code>findPaintingCategory</code> cache ID */
    private static int findPaintingCategoryDictionaryCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtEntryPointDictionary.Loader("findPaintingCategory"));

    /**
     * Gets the <code>findPaintingCategory</code> entry point dictionary descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the dictionary
     * @return the entry point dictionary descriptor object
     */
    public static com.matisse.reflect.MtEntryPointDictionary getFindPaintingCategoryDictionary(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtEntryPointDictionary)db.getCachedObject(findPaintingCategoryDictionaryCID);
    }

    /**
     * Finds the <code>PaintingCategory</code> object where <code>PaintingMedium</code> matches this value.
     * @param db a database
     * @param value the search string
     * @return the matching <code>PaintingCategory</code> or <code>null</code> if none was found
     * @throws MtException if more than one match found
     */
    public static PaintingCategory lookupFindPaintingCategory(com.matisse.MtDatabase db, String value) {
        return (PaintingCategory)getFindPaintingCategoryDictionary(db).lookup(value, getClass(db));
    }

    /**
     * Creates an iterator on all <code>PaintingCategory</code> objects where <code>PaintingMedium</code> matches this value.
     * @param <E> a MtObject class     * @param db a database
     * @param value the search string
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> findPaintingCategoryIterator(com.matisse.MtDatabase db, String value) {
        return getFindPaintingCategoryDictionary(db).<E>iterator(value, getClass(db), PaintingCategory.class);
    }

    /**
     * Creates an iterator on all <code>PaintingCategory</code> objects where <code>PaintingMedium</code> matches this value.
     * Use this method to restrict the iterator to members of a subclass of this class,
     * or to set a maximum number of objects.
     * @param <E> a MtObject class     * @param db a database
     * @param value the search string
     * @param filterClass a subclass; use <code>null</code> not to restrict iterator to a subclass
     * @param numObjPerBuffer maximum number of objects to include in the iterator
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> findPaintingCategoryIterator(com.matisse.MtDatabase db, String value, com.matisse.reflect.MtClass filterClass, int numObjPerBuffer) {
        return getFindPaintingCategoryDictionary(db).<E>iterator(value, filterClass, numObjPerBuffer, PaintingCategory.class);
    }


    /* Attribute 'PaintingFrame' */

    /** Attribute <code>PaintingFrame</code> cache ID */
    private static int paintingFrameCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("PaintingFrame",CID));

    /**
     * Gets the <code>PaintingFrame</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getPaintingFrameAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(paintingFrameCID);
    }


    /**
     * Gets the <code>PaintingFrame</code> attribute value.
     * @return the value
     *
     * @see #setPaintingFrame
     * @see #removePaintingFrame
     */
    public final String getPaintingFrame() {
        return getString(getPaintingFrameAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>PaintingFrame</code> attribute value.
     * @param val the new value
     *
     * @see #getPaintingFrame
     * @see #removePaintingFrame
     */
    public final void setPaintingFrame(String val) {
        setString(getPaintingFrameAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>PaintingFrame</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getPaintingFrame
     * @see #setPaintingFrame
     */
    public final void removePaintingFrame() {
        removeValue(getPaintingFrameAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getPaintingFrame
     * @see #setPaintingFrame
     */
    public final boolean isPaintingFrameDefaultValue() {
        return isDefaultValue(getPaintingFrameAttribute(getMtDatabase()));
    }


    /* Attribute 'PaintingDimension' */

    /** Attribute <code>PaintingDimension</code> cache ID */
    private static int paintingDimensionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("PaintingDimension",CID));

    /**
     * Gets the <code>PaintingDimension</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getPaintingDimensionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(paintingDimensionCID);
    }


    /**
     * Gets the <code>PaintingDimension</code> attribute value.
     * @return the value
     *
     * @see #setPaintingDimension
     * @see #removePaintingDimension
     */
    public final String getPaintingDimension() {
        return getString(getPaintingDimensionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>PaintingDimension</code> attribute value.
     * @param val the new value
     *
     * @see #getPaintingDimension
     * @see #removePaintingDimension
     */
    public final void setPaintingDimension(String val) {
        setString(getPaintingDimensionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>PaintingDimension</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getPaintingDimension
     * @see #setPaintingDimension
     */
    public final void removePaintingDimension() {
        removeValue(getPaintingDimensionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getPaintingDimension
     * @see #setPaintingDimension
     */
    public final boolean isPaintingDimensionDefaultValue() {
        return isDefaultValue(getPaintingDimensionAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'from_painting' */

    /** Relationship <code>from_painting</code> cache ID */
    private static int from_paintingCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("from_painting",CID));

    /**
     * Gets the <code>from_painting</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getFrom_paintingRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(from_paintingCID);
    }

    /**
     * Gets the <code>from_painting</code> sucessor object.
     * @return an object 
     */
    public final ArtItem getFrom_painting() {
        return (ArtItem)getSuccessor(getFrom_paintingRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public PaintingCategory(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[PaintingCategory]";
    }
}
