/*
 * PhotographicCategory.java
 *
 * Generated with Matisse Schema Definition Language 9.1.8
 * Generation date: Thu Apr 07 21:16:53 2016
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

import com.matisse.reflect.*;

/**
 * <code>PhotographicCategory</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class PhotographicCategory extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.8
     * Generation Date: Thu Apr 07 21:16:53 2016
     */

    /*
     * Class variables and methods
     */

    /** Class <code>PhotographicCategory</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("PhotographicCategory"));

    /**
     * Gets the <code>PhotographicCategory</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public PhotographicCategory(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected PhotographicCategory(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(PhotographicCategory.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, PhotographicCategory.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(PhotographicCategory.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, PhotographicCategory.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'PhotoType' */

    /** Attribute <code>PhotoType</code> cache ID */
    private static int photoTypeCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("PhotoType",CID));

    /**
     * Gets the <code>PhotoType</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getPhotoTypeAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(photoTypeCID);
    }


    /**
     * Gets the <code>PhotoType</code> attribute value.
     * @return the value
     *
     * @see #setPhotoType
     * @see #removePhotoType
     */
    public final String getPhotoType() {
        return getString(getPhotoTypeAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>PhotoType</code> attribute value.
     * @param val the new value
     *
     * @see #getPhotoType
     * @see #removePhotoType
     */
    public final void setPhotoType(String val) {
        setString(getPhotoTypeAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>PhotoType</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getPhotoType
     * @see #setPhotoType
     */
    public final void removePhotoType() {
        removeValue(getPhotoTypeAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getPhotoType
     * @see #setPhotoType
     */
    public final boolean isPhotoTypeDefaultValue() {
        return isDefaultValue(getPhotoTypeAttribute(getMtDatabase()));
    }

    /* EntryPoint 'findPhotographicCategory' of attribute 'PhotoType' */

    /** EntryPointDictionary <code>findPhotographicCategory</code> cache ID */
    private static int findPhotographicCategoryDictionaryCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtEntryPointDictionary.Loader("findPhotographicCategory"));

    /**
     * Gets the <code>findPhotographicCategory</code> entry point dictionary descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the dictionary
     * @return the entry point dictionary descriptor object
     */
    public static com.matisse.reflect.MtEntryPointDictionary getFindPhotographicCategoryDictionary(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtEntryPointDictionary)db.getCachedObject(findPhotographicCategoryDictionaryCID);
    }

    /**
     * Finds the <code>PhotographicCategory</code> object where <code>PhotoType</code> matches this value.
     * @param db a database
     * @param value the search string
     * @return the matching <code>PhotographicCategory</code> or <code>null</code> if none was found
     * @throws MtException if more than one match found
     */
    public static PhotographicCategory lookupFindPhotographicCategory(com.matisse.MtDatabase db, String value) {
        return (PhotographicCategory)getFindPhotographicCategoryDictionary(db).lookup(value, getClass(db));
    }

    /**
     * Creates an iterator on all <code>PhotographicCategory</code> objects where <code>PhotoType</code> matches this value.
     * @param <E> a MtObject class     * @param db a database
     * @param value the search string
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> findPhotographicCategoryIterator(com.matisse.MtDatabase db, String value) {
        return getFindPhotographicCategoryDictionary(db).<E>iterator(value, getClass(db), PhotographicCategory.class);
    }

    /**
     * Creates an iterator on all <code>PhotographicCategory</code> objects where <code>PhotoType</code> matches this value.
     * Use this method to restrict the iterator to members of a subclass of this class,
     * or to set a maximum number of objects.
     * @param <E> a MtObject class     * @param db a database
     * @param value the search string
     * @param filterClass a subclass; use <code>null</code> not to restrict iterator to a subclass
     * @param numObjPerBuffer maximum number of objects to include in the iterator
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> findPhotographicCategoryIterator(com.matisse.MtDatabase db, String value, com.matisse.reflect.MtClass filterClass, int numObjPerBuffer) {
        return getFindPhotographicCategoryDictionary(db).<E>iterator(value, filterClass, numObjPerBuffer, PhotographicCategory.class);
    }


    /* Attribute 'PhotoDimension' */

    /** Attribute <code>PhotoDimension</code> cache ID */
    private static int photoDimensionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("PhotoDimension",CID));

    /**
     * Gets the <code>PhotoDimension</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getPhotoDimensionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(photoDimensionCID);
    }


    /**
     * Gets the <code>PhotoDimension</code> attribute value.
     * @return the value
     *
     * @see #setPhotoDimension
     * @see #removePhotoDimension
     */
    public final String getPhotoDimension() {
        return getString(getPhotoDimensionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>PhotoDimension</code> attribute value.
     * @param val the new value
     *
     * @see #getPhotoDimension
     * @see #removePhotoDimension
     */
    public final void setPhotoDimension(String val) {
        setString(getPhotoDimensionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>PhotoDimension</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getPhotoDimension
     * @see #setPhotoDimension
     */
    public final void removePhotoDimension() {
        removeValue(getPhotoDimensionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getPhotoDimension
     * @see #setPhotoDimension
     */
    public final boolean isPhotoDimensionDefaultValue() {
        return isDefaultValue(getPhotoDimensionAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'from_photo' */

    /** Relationship <code>from_photo</code> cache ID */
    private static int from_photoCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("from_photo",CID));

    /**
     * Gets the <code>from_photo</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getFrom_photoRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(from_photoCID);
    }

    /**
     * Gets the <code>from_photo</code> sucessor object.
     * @return an object 
     */
    public final ArtItem getFrom_photo() {
        return (ArtItem)getSuccessor(getFrom_photoRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public PhotographicCategory(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[PhotographicCategory]";
    }
}
